### ISSUE TITLE
Filter on MutableObservableArray breaks batch editing updates

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/Bond#377]
```swift
let collection = MutableObservableArray<String>(["A","B","C"])

collection.filter {_ in return true}.observeNext { (event) in
    print("Event: \(event.change)")
}

collection.replace(with: [], performDiff: true)
```

*Should* output: 

	Event: reset
	Event: beginBatchEditing
	Event: deletes([0,1,2])
	Event: endBatchEditing

or, perhaps:

	Event: reset
	Event: beginBatchEditing
	Event: deletes([0])
	Event: deletes([1])
	Event: deletes([2])
	Event: endBatchEditing

**But it actually outputs:**

	Event: reset
	Event: beginBatchEditing
	Event: deletes([0])
	Event: endBatchEditing

**However, when I remove the `filter`, it works correctly:**

	Event: reset
	Event: beginBatchEditing
	Event: deletes([0])
	Event: deletes([1])
	Event: deletes([2])
	Event: endBatchEditing

**Comment by iandundas** [comment]
Sorry - this is on Bond v5.4.4 (latest)

**Comment by srdanrasic** [comment]
That looks :(

**Comment by srdanrasic** [comment]
Just pushed v5.4.5 with the fix. Collections are hard.

Thanks for the detailed issue report! :)

**Comment by iandundas** [comment]
Event: reset
	Event: beginBatchEditing
	Event: deletes([0])
	Event: deletes([1])
	Event: deletes([2])
	Event: endBatchEditing

🙏🏼 thanks!

**Comment by iandundas** [comment]
Though a heads-up man, it's also there in Bond 6 beta 3 😔

```
Event: reset
Event: beginBatchEditing
Event: deletes([0])
Event: endBatchEditing
```

**Comment by srdanrasic** [comment]
Ok, I've just merged fixes. You can use "master" if you wish instead of latest beta. I hope I'll release v6 over the weekend. Need to do some final tests :)

**Comment by iandundas** [comment]
Hey again,

Think there's still an issue, again caused by `.filter`, and in both 5 and 6: 

```swift

let collection = MutableObservableArray<String>([])

collection.filter {_ in return true}.observeNext { (event) in
    print("Event: \(event.change)")
}

collection.replace(with: ["hello"], performDiff: true)

```

Produces: 

    Event: reset
    Event: beginBatchEditing
    Event: endBatchEditing

**Comment by srdanrasic** [comment]
You found a deeper problem :) I'm working on it...

**Comment by iandundas** [comment]
# 🕵🏻💫

cool :)

**Comment by srdanrasic** [comment]
Forgot to tell you, but this should be fixed in v5.4.6 and v6.

**Comment by iandundas** [comment]
great work, thanks!!
